# Generated by Django 2.1.7 on 2019-06-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0007_vhosts_confd_vhosts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vhostsconfd',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='confd.ProjectConfd', verbose_name='项目名称'),
        ),
    ]
